teacher:
  name: cartpole_x_gaussian
  class: teacher.cartpole.CartpoleXGaussianTeachers
  params:
    n_experts: 2
    n_generalists: 0
    ds: ???
    da: ???
    gamma: 1
    eps_mistake: 0
    eps_skip: 0
    eps_equal: 0
    beta_general: 1
    scale: 1
    thresh_val: 0.1
