teacher:
  name: grasping
  class: teacher.grasp.GraspingTeachers
  params:
        grasp_thresh: 0.5
        ds: ???
        da: ???
        beta_1: [10, 10]
        beta_2: [0.1, 0.1]
        gamma: [1, 1]
        eps_mistake: [0, 0]
        eps_skip: [0, 0]
        eps_equal: [0, 0]