teacher:
  name: grasping_inplace
  class: teacher.grasp_inplace.GraspingInPlaceOnlyTeachers
  params:
        ds: ???
        da: ???
        beta: [1, 1]
        gamma: [1, 1]
        eps_mistake: [0, 0]
        eps_skip: [0, 0]
        eps_equal: [0, 0]
        sampling: uniform