teacher:
  name: reward_beta
  class: teacher.reward_beta.RewardBetaTeachers
  params:
        reward_keys: [grasp_reward, in_place_reward]
        ds: ???
        da: ???
        beta_scale: [1, 1]
        gamma: [1, 1]
        eps_mistake: 0
        eps_skip: 0
        eps_equal: 0
        sampling: uniform